export const SET_LOGIN = 'SET_LOGIN'
export const SET_ISLOGIN = 'SET_ISLOGIN'
export const SET_SELECTED_ADMIN = 'SET_SELECTED_ADMIN'
export const SET_SELECTED_PLATFORM = 'SET_SELECTED_PLATFORM'
export const SET_LOGOUT = 'SET_LOGOUT'
// export const SET_PRODUCTS = 'SET_PRODUCTS'

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_CHANGE_ADMIN = 'SET_CHANGE_ADMIN'
export const SET_CHANGE_PRODUCT = 'SET_CHANGE_PRODUCT'
export const SET_CHANGE_TOP_CHANNELS = 'SET_CHANGE_TOP_CHANNELS'
export const SET_CHANGE_SUB_CHANNELS = 'SET_CHANGE_SUB_CHANNELS'
export const SET_CHANGE_DATE = 'SET_CHANGE_DATE'

export const SET_BASEDATE = 'SET_BASEDATE'
